#!/usr/bin/env python3
"""slot0nm: slot0clean (definition-A contamination regenerated) with every guessed
measurement removed: numbers (BPM, Hz, dB, durations), musical key / mode, and meter
/ time signature. Operator 2026-09-16: a captioning LM cannot measure BPM, key or
meter, so these details are fabricated and must not reach training.

Base caption per row:
  - row untouched by the cleanup  -> slot4v2 caption (digits already removed and QA'd;
    its "4/4 -> common time" and kept "key of D major" are removed here)
  - row regenerated by the cleanup -> regenerated caption (digits handled here)
Sentence-level, same discipline as slot4v2: sentences with no MEASURE match are copied
byte-identical (asserted). Each MEASURE sentence goes alone to Qwen2.5-32B-Instruct-AWQ
(vLLM); an output is accepted only if it passes hard gates. Otherwise a deterministic
phrase cut is tried on the ORIGINAL sentence, else the sentence is dropped. A row whose
every sentence is dropped is listed as excluded (never silently emptied).
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/preprocess"))
csv.field_size_limit(10**9)

SENT_SPLIT = re.compile(r"(?<=[.!?])(\s+)")
NOTE = r"(?-i:[A-G])(?:#|♯|(?-i:b)|♭|\s+sharp|\s+flat)?"  # note letter is case-sensitive: "a major role" is not A major
MEASURE = re.compile(
    r"\d"
    r"|\bbpms?\b|beats?[\s-]+per[\s-]+minute|\bhertz\b|\bk?hz\b|\bdecibels?\b|\bdb\b"
    r"|\bkeys? of (?-i:[A-G])(?![a-z])|\bkeys? (?:signatures?|changes?|modulations?)\b|\bin the (?:same |original |home )?key\b"
    r"|\b(?:major|minor|same|different|relative|parallel|home|original|new|higher|lower) keys?\b"
    r"|\btonality\b|\btonal (?:center|centre)\b|\bmodality\b"
    r"|\b(?:major|minor)(?: and (?:major|minor))? (?:chords?|thirds?|sixths?|sevenths?|triads?|progressions?|intervals?)\b"
    r"|\bin (?:a|the) (?!low\b)[\w-]+ key\b"
    rf"|(?<![\w-]){NOTE}[\s-]+(?:major|minor|dorian|mixolydian|phrygian|lydian|aeolian|ionian|locrian)\b"
    r"|\b(?:major|minor) (?:scale|mode|chord progression|tonality|key)\b|\bin (?:a )?(?:major|minor)\b"
    r"|time signature|\b(?:common|waltz|cut|duple|triple|compound|irregular|odd) time\b|\bmet(?:er|re)\b"
    r"|\b(?:four|three|six|two|five|seven|nine|twelve)[\s-](?:four|eight|two)(?: time)?\b",
    re.I,
)
INJECTION = re.compile(
    r"\?|\n|\b(?:user|assistant|human|system)\s*:|\b(?:input|output|rewrite|sentence|caption|note)\s*:|"
    r"\b(?:answer the|write (?:a|the|an)|create a|translate|choose one|given the|here is)\b",
    re.I,
)
DANGLING = re.compile(
    r"(?<![\w-])(?:is|are|was|were|be|set|has|have|having|at|of|with|in|by|to|and|or|a|an|the|than|"
    r"from|between|around|about|approximately|roughly|nearly|possibly|likely)\s*[,.;:!]"
    r"|\b(?:a|an|the)\s+(?:\w+\s+)?(?:fast|slow|moderate|quick|steady|consistent|high|low|medium|rapid)\s*[,.;:!]"
    r"|\b(?:primarily|mainly|predominantly|mostly|largely|probably|typically|usually|often)\s*[,.;:!]"
    r"|,\s*[,.]|^\W|\(\s*\)|\bwith the (?:music|song|track|piece|audio)\s*[.!]$",
    re.I,
)
STOP = {"a", "an", "the", "and", "or", "of", "with", "in", "at", "is", "to", "its", "it", "this", "that",
        "which", "by", "for", "on", "as", "are", "has", "have", "while", "be", "was", "there", "also"}
MEASURE_WORDS = {"bpm", "beats", "beat", "per", "minute", "key", "keys", "major", "minor", "scale", "mode",
                 "tonality", "time", "signature", "common", "waltz", "cut", "meter", "metre", "duple",
                 "triple", "compound", "irregular", "tempo", "around", "about", "approximately", "set",
                 "sharp", "flat", "hz", "khz", "db", "hertz", "decibels", "played", "performed", "written",
                 "composed", "range", "estimated", "consistent", "steady", "signatures", "tonal", "center"}
ALLOWED_NOVEL = {"fast", "slow", "tempo", "pace", "fast-paced", "quick"}

SYSTEM = """\
Edit ONE sentence from a music caption. Delete every musical MEASUREMENT the captioning
model could only have guessed:
- numbers and numeric values: BPM, beats per minute ("high BPM", "a few hundred beats per
  minute"), Hz, dB, durations, time stamps
- musical key, mode or chord quality: "in the key of C minor", "in D major", "in a minor
  key", "major scale", "tonality", "minor chords", "a minor chord progression" (keep
  "chord progression" itself)
- meter or time signature: "4/4", "common time", "waltz time", "a 3/4 time signature"
Keep every other word exactly as written, in the same order, and keep the sentence
grammatical. Qualitative tempo words already present (fast, slow, moderate, upbeat) stay.
"high BPM" / "fast BPM" may become "fast tempo". Do not add instruments, genres, moods,
tempo words or quality claims. Keep "four-on-the-floor" (a drum pattern) and decade words
("eighties"). If nothing descriptive is left, answer exactly NONE. Answer with the edited
sentence only."""

FEW_SHOT = [
    ("The performance is in the key of D major, in common time.", "NONE"),
    ("The music is a lively pop track in A minor, in common time.", "The music is a lively pop track."),
    ("The tempo is moderate, while the music is in A minor, in common time.", "The tempo is moderate."),
    ("It has a key of D minor and a common time signature.", "NONE"),
    ("The music features a string section with violins playing a soft, sustained melody in the key of C minor.",
     "The music features a string section with violins playing a soft, sustained melody."),
    ("The music has a high BPM with a fast tempo, creating an exhilarating atmosphere.",
     "The music has a fast tempo, creating an exhilarating atmosphere."),
    ("The tempo is fast and upbeat, with a consistent 120 BPM.", "The tempo is fast and upbeat."),
    ("The audio is a 116.48 bpm funk track in the key of C major, with a 4/4 time signature featuring electric guitars, drums, bass guitar, and keyboards.",
     "The audio is a funk track featuring electric guitars, drums, bass guitar, and keyboards."),
    ("A clean electric guitar plays a melodic, minor chord progression that intensifies throughout the clip.",
     "A clean electric guitar plays a melodic chord progression that intensifies throughout the clip."),
    ("A gentle acoustic guitar piece is played in a minor key, creating a serene atmosphere.",
     "A gentle acoustic guitar piece is played, creating a serene atmosphere."),
    ("A soft guitar strums in a minor key, accompanied by a smooth synth pad.",
     "A soft guitar strums, accompanied by a smooth synth pad."),
]

# Deterministic phrase cuts on the original sentence (applied in order, then tidy).
CUTS = [
    re.compile(rf",?\s*(?:and\s+|which\s+is\s+|that\s+is\s+)?(?:played\s+|performed\s+|written\s+|composed\s+|set\s+)?in\s+(?:the\s+)?(?:key\s+of\s+)?{NOTE}[\s-]+(?:major|minor)(?:\s+key)?", re.I),
    re.compile(r",?\s*(?:and\s+)?(?:played\s+|performed\s+|set\s+)?in\s+(?:(?:a|the)\s+)?(?:major|minor)\s+(?:key|scale|mode|tonality)", re.I),
    re.compile(r"\b(?:major|minor)(?:\s+and\s+(?:major|minor))?\s+(?=(?:chords?|chord\s+progressions?|progressions?|thirds?|triads?|sixths?|sevenths?|intervals?)\b)", re.I),
    re.compile(r",?\s*(?:and\s+|with\s+)?(?:a|an|the)\s+(?:[\w-]+\s+)?time\s+signature(?:\s+of\s+\S+)?", re.I),
    re.compile(r",?\s*(?:and\s+)?(?:played\s+|set\s+)?in\s+(?:common|waltz|cut|duple|triple|compound|irregular)\s+time", re.I),
    re.compile(r",?\s*(?:with\s+|at\s+|and\s+)?(?:a\s+)?(?:tempo\s+of\s+)?(?:approximately\s+|around\s+|about\s+)?[\d.]+\s*(?:bpm|beats\s+per\s+minute)", re.I),
]


def tidy(text: str) -> str:
    out = re.sub(r"\s{2,}", " ", text)
    out = re.sub(r"\s+([,.;:!?])", r"\1", out)
    out = re.sub(r"([,;:])\s*([,.;:!?])", r"\2", out)
    out = re.sub(r"^\s*[,;:]\s*", "", out).strip()
    if out and out[0].islower():
        out = out[0].upper() + out[1:]
    if out and not out.endswith((".", "!")):
        out = out.rstrip(",;: ") + "."
    return out


def words(text: str) -> list[str]:
    return re.findall(r"[a-z][a-z'\-]*", text.lower())


def stem(w: str) -> str:
    for suf in ("ing", "ed", "es", "s"):
        if w.endswith(suf) and len(w) > len(suf) + 2:
            return w[: -len(suf)]
    return w


def gate(src: str, dst: str) -> list[str]:
    """Reasons to reject; empty list = accept. dst == 'NONE' handled by caller."""
    why = []
    if MEASURE.search(dst):
        why.append("measure_left")
    if INJECTION.search(dst) and not INJECTION.search(src):
        why.append("injection")
    if len(DANGLING.findall(dst)) > len(DANGLING.findall(src)):
        why.append("dangling")
    if len(SENT_SPLIT.split(dst.strip())) > 1:
        why.append("multi_sentence")
    if not dst.strip().endswith((".", "!")):
        why.append("no_terminal")
    if len(dst.split()) > len(src.split()):
        why.append("longer")
    src_stems = {stem(w) for w in words(src)}
    novel = [w for w in words(dst) if stem(w) not in src_stems and w not in STOP]
    if len([w for w in novel if w not in ALLOWED_NOVEL]) > 0 or len(novel) > 2:
        why.append(f"novel:{','.join(novel[:3])}")
    lost = {stem(w) for w in words(src) if w not in STOP and w not in MEASURE_WORDS
            and not re.fullmatch(r"[a-g](?:#|b)?", w)} - {stem(w) for w in words(dst)}
    if len(lost) > 2:
        why.append(f"lost:{','.join(sorted(lost)[:4])}")
    return why


def none_ok(src: str) -> bool:
    rest = [w for w in words(src) if w not in STOP and w not in MEASURE_WORDS
            and not re.fullmatch(r"[a-g](?:#|b)?|sharp|flat|music|song|track|piece|audio|performance|clip", w)]
    return len(rest) <= 2


def clause_drop(src: str) -> str | None:
    """Last resort before dropping a sentence: remove only comma clauses that hold a measurement."""
    parts = re.split(r",\s+", src.strip())
    if MEASURE.search(parts[0]):
        head = parts[0]
        for pat in CUTS:
            head = pat.sub("", head)
        if MEASURE.search(head):
            return None
        parts[0] = head
    kept = [parts[0]] + [p for p in parts[1:] if not MEASURE.search(p)]
    out = tidy(", ".join(kept))
    if MEASURE.search(out) or (INJECTION.search(out) and not INJECTION.search(src)):
        return None
    if len(DANGLING.findall(out)) > len(DANGLING.findall(src)) or not out.endswith((".", "!")):
        return None
    content = [w for w in words(out) if w not in STOP and w not in MEASURE_WORDS]
    return out if len(content) >= 4 else None


def cut_sentence(src: str) -> str | None:
    out = src
    for pat in CUTS:
        out = pat.sub("", out)
    out = tidy(out)
    if not out or gate(src, out):
        return None
    return out


class Engine:
    def __init__(self, model: str):
        from vllm import LLM, SamplingParams
        self.SP = SamplingParams
        self.llm = LLM(model=model, max_model_len=4096, gpu_memory_utilization=0.88,
                       enable_prefix_caching=True, seed=0)

    def run(self, sentences: list[str], temperature: float, seed: int) -> list[str]:
        shots = []
        for a, b in FEW_SHOT:
            shots += [{"role": "user", "content": a}, {"role": "assistant", "content": b}]
        convs = [[{"role": "system", "content": SYSTEM}, *shots, {"role": "user", "content": s}] for s in sentences]
        params = self.SP(temperature=temperature, max_tokens=160, seed=seed)
        outs = self.llm.chat(convs, params, use_tqdm=True)
        return [(o.outputs[0].text.strip() if o.outputs[0].finish_reason == "stop" else "") for o in outs]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean-tsv", type=Path, required=True, help="slot0clean train TSV (251,599 rows)")
    ap.add_argument("--source-tsv", type=Path, required=True, help="original slot0 TSV")
    ap.add_argument("--slot4v2-tsv", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--model", default=str(next(Path.home().glob(
        ".cache/huggingface/hub/models--Qwen--Qwen2.5-32B-Instruct-AWQ/snapshots/*"), "")))
    ap.add_argument("--attempts", type=int, default=4)
    ap.add_argument("--limit", type=int, default=0, help="first N measure sentences only (dry run)")
    ap.add_argument("--redo-drops", action="store_true", help="re-run sentences whose logged result was drop")
    args = ap.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    read = lambda p: list(csv.DictReader(p.open(encoding="utf-8", newline=""), delimiter="\t"))  # noqa: E731
    clean, source, v2 = read(args.clean_tsv), read(args.source_tsv), read(args.slot4v2_tsv)
    assert [r["id"] for r in clean] == [r["id"] for r in source] == [r["id"] for r in v2], "row order differs"
    base_rows, origin = [], Counter()
    for c, s, v in zip(clean, source, v2):
        if c["caption"] == s["caption"]:
            base_rows.append({**c, "caption": v["caption"]}); origin["slot4v2"] += 1
        else:
            base_rows.append(dict(c)); origin["regenerated"] += 1

    units = {}  # sentence text -> result (dedupe identical sentences)
    for r in base_rows:
        for s in SENT_SPLIT.split(r["caption"])[0::2]:
            if MEASURE.search(s):
                units.setdefault(s, None)
    todo = sorted(units)
    if args.limit:
        todo = todo[: args.limit]
    print(json.dumps({"rows": len(base_rows), "origin": origin, "measure_sentences_unique": len(units),
                      "todo": len(todo)}), flush=True)

    log_path = args.out_dir / "sentence_log.jsonl"
    done = {}
    if log_path.exists():
        for line in log_path.read_text().splitlines():
            rec = json.loads(line)
            stale = rec["dst"] and (MEASURE.search(rec["dst"])
                                    or len(DANGLING.findall(rec["dst"])) > len(DANGLING.findall(rec["src"])))
            if "--redo-drops" in sys.argv and (rec["method"] == "drop" or stale):
                done.pop(rec["src"], None)  # later clause_drop fallback may salvage it
                continue
            done[rec["src"]] = rec
    pending = [s for s in todo if s not in done]
    last_reason = {}
    if pending:
        eng = Engine(args.model)
        for attempt in range(args.attempts):
            if not pending:
                break
            temp = 0.0 if attempt == 0 else 0.3 + 0.2 * (attempt - 1)
            outs = eng.run(pending, temp, seed=attempt)
            still = []
            with log_path.open("a") as fh:
                for s, o in zip(pending, outs):
                    rec = None
                    if o == "NONE":
                        if none_ok(s):
                            rec = {"src": s, "dst": None, "method": "llm_none", "attempt": attempt}
                        else:
                            last_reason[s] = "none_rejected"
                    elif o:
                        o = tidy(o)
                        why = gate(s, o)
                        if not why:
                            rec = {"src": s, "dst": o, "method": "llm", "attempt": attempt}
                        else:
                            last_reason[s] = why
                    else:
                        last_reason[s] = "empty_or_truncated"
                    if rec:
                        fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        done[s] = rec
                    else:
                        still.append(s)
            pending = still
            print(json.dumps({"attempt": attempt, "accepted": len(todo) - len(pending), "pending": len(pending)}),
                  flush=True)
        with log_path.open("a") as fh:
            for s in pending:
                cut = cut_sentence(s)
                cl = None if cut else clause_drop(s)
                rec = ({"src": s, "dst": cut, "method": "cut", "llm_reason": last_reason.get(s)} if cut else
                       {"src": s, "dst": cl, "method": "clause_drop", "llm_reason": last_reason.get(s)} if cl else
                       {"src": s, "dst": None, "method": "drop", "llm_reason": last_reason.get(s)})
                fh.write(json.dumps(rec, ensure_ascii=False, default=str) + "\n")
                done[s] = rec
    if args.limit:
        print("limit set: dry run, no corpus written")
        return 0

    out_rows, excluded, stats = [], [], Counter()
    for r in base_rows:
        parts = SENT_SPLIT.split(r["caption"])
        sents = parts[0::2]
        kept = []
        for s in sents:
            if not MEASURE.search(s):
                kept.append(s)
                continue
            rec = done[s]
            stats[rec["method"]] += 1
            if rec["dst"]:
                kept.append(rec["dst"])
        if not kept:
            excluded.append({"id": r["id"], "caption": r["caption"]})
            continue
        cap = " ".join(kept)
        out_rows.append({**r, "caption": cap})

    # audit: no measurement anywhere, measure-free sentences byte-identical and in order
    base_by_id = {r["id"]: r["caption"] for r in base_rows}
    for r in out_rows:
        if MEASURE.search(r["caption"]):
            raise SystemExit(f"[FAIL] measurement left in {r['id']}: {r['caption']!r}")
        clean_sents = [s for s in SENT_SPLIT.split(base_by_id[r["id"]])[0::2] if not MEASURE.search(s)]
        pos = 0
        for s in clean_sents:
            idx = r["caption"].find(s, pos)
            if idx < 0:
                raise SystemExit(f"[FAIL] measure-free sentence lost/reordered in {r['id']}: {s!r}")
            pos = idx + len(s)
        if INJECTION.search(r["caption"]) and not INJECTION.search(base_by_id[r["id"]]):
            raise SystemExit(f"[FAIL] injection marker introduced in {r['id']}")

    out_tsv = args.out_dir / "phase8_caption2p0_slot0nm_train.tsv"
    tmp = out_tsv.with_name("." + out_tsv.name + ".tmp")
    with tmp.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(clean[0].keys()), delimiter="\t", lineterminator="\n")
        w.writeheader()
        w.writerows(out_rows)
    os.replace(tmp, out_tsv)
    (args.out_dir / "excluded_rows.json").write_text(json.dumps(excluded, ensure_ascii=False, indent=1))
    changed = sum(1 for r in out_rows if r["caption"] != base_by_id[r["id"]])
    summary = {"status": "rewrite_complete_not_released", "rows_in": len(base_rows), "rows_out": len(out_rows),
               "excluded_all_sentences_dropped": len(excluded), "origin": origin,
               "rows_changed_vs_base": changed, "sentence_methods": stats,
               "unique_sentences": Counter(v["method"] for v in done.values()),
               "model": args.model}
    (args.out_dir / "summary.json").write_text(json.dumps(summary, indent=1))
    print(json.dumps(summary), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
