#!/bin/bash
# ============================================================
# MeanAudio Phase 9.5 V2 — task-framed Qwen multi-cap, Q=MeanSim
# train_pipeline_phase9_5_v2.sh
#
# GATED LAUNCH (per Codex 2026-05-03 sequential gating):
#   Only launch this V2 if P9.5 V1 results show:
#     - MusicCaps CLAP > 0.0650 (better than P9 V1 bugfix), OR
#     - same-seed prompt steering ratio > 0.2 (no text-conditioning collapse)
#   If V1 already collapses, V2 will likely confirm failure → save GPU.
#
# Differences from V1:
#   - USE_Q_CONDITIONING=true (q_embed pathway active)
#   - TRAIN_TSV = phase9_5_v2_train.tsv (Qwen-local percentile q_level 0..9)
#     ↑ MUST be generated by gen_phase9_5_q_levels.py BEFORE running this
#   - Eval: q sweep {6, 9} on MusicCaps + Jamendo seed42
#     (q=6 in-support boundary, q=9 high-confidence; per P7 V1 q-sweep pattern)
#
# Pre-flight assumes:
#   - P9.5 V1 finished (so V1 NPZ + bug fixes are validated)
#   - phase9_5_v2_train.tsv exists with proper q_level (not dummy q=5)
#   - phase9_5_multicap_npz/ shared with V1 (same Qwen captions)
#
# Per Codex 2026-05-03: q=N is captioner-LOCAL percentile bucket.
#   Do NOT directly compare q=N CLAP across captioners (LP-MC vs Qwen).
#   Report raw mean_sim distribution + bin edges (saved by gen script).
#
# Usage:
#   tmux new -s p9_5_v2
#   cd ~/MeanAudio && source ~/venvs/dac/bin/activate
#   bash train_pipeline_phase9_5_v2.sh
# ============================================================

set -eo pipefail

# ============================================================
# 實驗參數
# ============================================================

EXP_PREFIX="phase9_5_v2"

BATCH_SIZE=8
ACCUM_STEPS=1

S1_ITERATIONS=400000
S2_ITERATIONS=200000

LEARNING_RATE=1e-4
USE_Q_CONDITIONING=true   # V2 trains q_embed[0..9] from MeanSim of 5 Qwen caps

# ============================================================
# 固定路徑
# ============================================================

WORK_DIR="$HOME/MeanAudio"
DATA_DIR="/mnt/HDD/kojiek/phase4_jamendo_data"
LOG_DIR="$HOME/logs"

EXP_S1="${EXP_PREFIX}_stage1_${S1_ITERATIONS}"
EXP_S2="${EXP_PREFIX}_stage2_${S2_ITERATIONS}"

S1_CKPT="$WORK_DIR/exps/$EXP_S1/${EXP_S1}_ckpt_last.pth"
S2_CKPT="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ckpt_last.pth"
S2_EMA="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ema_final.pth"

MIGRATE_SCRIPT="$WORK_DIR/migrate_stage1_to_stage2_ckpt.py"
STAGE_SCRIPT="$WORK_DIR/set_training_stage.py"

MULTICAP_NPZ="$HOME/phase9_5_multicap_npz"     # shared with V1
EVAL_SCRIPT="$HOME/research/meanaudio_eval/phase4_eval.py"

# V2-specific TSV with real Qwen-local q_level (NOT the V1 dummy)
TRAIN_TSV="$DATA_DIR/phase9_5_v2_train.tsv"
VAL_TSV="$DATA_DIR/phase4_val.tsv"
TSV_MUSICCAPS="$DATA_DIR/musiccaps_test.tsv"
TSV_JAMENDO_S42="$DATA_DIR/phase4_test_seed42_2048.tsv"

S1_MACRO=$(( S1_ITERATIONS / ACCUM_STEPS ))
S2_MACRO=$(( S2_ITERATIONS / ACCUM_STEPS ))

COMMON_ARGS=(
    batch_size=$BATCH_SIZE
    +accumulation_steps=$ACCUM_STEPS
    learning_rate=$LEARNING_RATE
    num_workers=4
    save_weights_interval=10000
    save_checkpoint_interval=20000
    +use_rope=False
    +use_wandb=False
    "+use_q_conditioning=$USE_Q_CONDITIONING"
    val_interval=999999
    eval_interval=999999
    save_eval_interval=999999
    "data.AudioCaps_npz.tsv=$TRAIN_TSV"
    "data.AudioCaps_val_npz.tsv=$VAL_TSV"
    "++data.AudioCaps_npz.npz_dir=$MULTICAP_NPZ"
    "++multi_cap=True"
)

mkdir -p "$LOG_DIR" "$WORK_DIR/exps/$EXP_S1" "$WORK_DIR/exps/$EXP_S2"
cd "$WORK_DIR"
export CUDA_VISIBLE_DEVICES=0

echo "======================================================"
echo "  Phase 9.5 V2 — task-framed Qwen multi-cap, Q=MeanSim"
echo "  S1 exp_id    : $EXP_S1 (from scratch, with Q)"
echo "  S2 exp_id    : $EXP_S2"
echo "  NPZ dir      : $MULTICAP_NPZ (shared with V1)"
echo "  Train TSV    : $TRAIN_TSV (Qwen-local q_level)"
echo "  use_q_cond   : $USE_Q_CONDITIONING"
echo "  Eval         : MusicCaps + Jamendo seed42, q={6,9}"
echo "======================================================"

# ============================================================
# Pre-flight A: bug fixes still applied
# ============================================================
echo "[Pre-flight A] verify bug fixes"

python -c "
import re
with open('meanaudio/model/networks.py') as f:
    code = f.read()
mf_start = code.find('class MeanAudio')
mf_code = code[mf_start:]
if re.search(r'q = torch\.full\(\([^,]+,\), 9,', mf_code):
    raise SystemExit('[FAIL] networks.py MeanAudio still fills q=9 instead of 10')
print('[OK] networks.py q=10 fix active')
"

python -c "
with open('meanaudio/runner_meanflow.py') as f:
    code = f.read()
if 'text_f_undrop = text_f.clone()' not in code or 'text_f_c_undrop = text_f_c.clone()' not in code:
    raise SystemExit('[FAIL] runner_meanflow.py text_f_undrop alias bug present')
print('[OK] runner_meanflow.py clone fix active')
"

python -c "
with open('meanaudio/runner_flowmatching.py') as f:
    code = f.read()
if 'q_level' not in code:
    raise SystemExit('[FAIL] runner_flowmatching.py missing q_level reads')
print('[OK] runner_flowmatching.py q passing active (S1 actually trains q_embed[0..9])')
"

# ============================================================
# Pre-flight B: V2 train TSV must exist with real q_level (not V1 dummy)
# ============================================================
echo "[Pre-flight B] verify V2 train TSV has real q_level distribution"

if [ ! -f "$TRAIN_TSV" ]; then
    echo "[FAIL] $TRAIN_TSV not found"
    echo "       Run first: python ~/research/meanaudio_training/gen_phase9_5_q_levels.py"
    exit 1
fi

python -c "
import csv, sys
from collections import Counter
with open('$TRAIN_TSV') as f:
    rows = list(csv.DictReader(f, delimiter='\t'))
counts = Counter(r['q_level'] for r in rows)
print(f'  rows: {len(rows):,}')
print(f'  q_level distribution: {dict(sorted(counts.items()))}')
unique_q = len(counts)
if unique_q < 5:
    print(f'[FAIL] only {unique_q} unique q values — looks like V1 dummy TSV')
    print('       Run: python ~/research/meanaudio_training/gen_phase9_5_q_levels.py')
    sys.exit(1)
print(f'[OK] {unique_q} q bins populated (Qwen-local percentile-equal-frequency)')
"

# ============================================================
# Pre-flight C: NPZ
# ============================================================
echo "[Pre-flight C] verify NPZ dir"
python "$HOME/research/meanaudio_training/validate_multicap_npz.py" \
    --tsv "$TRAIN_TSV" --npz_dir "$MULTICAP_NPZ" --deep 200

# ============================================================
# Stage 1 — FluxAudio with Q (S1 trains q_embed[0..9] from data q_level)
# ============================================================
echo "[Stage 1] launching $EXP_S1"
python "$STAGE_SCRIPT" --stage 1

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=fluxaudio_s \
    exp_id="$EXP_S1" \
    num_iterations=$S1_ITERATIONS \
    "lr_schedule_steps=[320000,360000]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S1}.log"

echo "[Stage 1] done. ckpt at $S1_CKPT"

# ============================================================
# Migrate (preserves trained q_embed[0..9])
# ============================================================
echo "[Migrate] $S1_CKPT → $S2_CKPT"
python "$MIGRATE_SCRIPT" --s1_ckpt "$S1_CKPT" --s2_out "$S2_CKPT"

# ============================================================
# Stage 2 — MeanAudio with Q
# ============================================================
echo "[Stage 2] launching $EXP_S2"
python "$STAGE_SCRIPT" --stage 2

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=meanaudio_s \
    exp_id="$EXP_S2" \
    num_iterations=$(( S1_ITERATIONS + S2_ITERATIONS )) \
    "lr_schedule_steps=[999999,999999]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S2}.log"

echo "[Stage 2] done"

# ============================================================
# Eval: q sweep {6, 9} × {MusicCaps, Jamendo seed42}
#   q=6: in-support boundary (per P7 V1 q-sweep pattern, support-set gating)
#   q=9: high-confidence end (P9 V2 baseline)
# ============================================================
for Q in 6 9; do
    # ── MusicCaps q=$Q ──────────────────────────────────────
    EVAL_OUT_MC="$WORK_DIR/eval_output/${EXP_S2}_q${Q}_musiccaps"
    echo "[Eval MusicCaps q=$Q] gen → $EVAL_OUT_MC"

    python eval.py \
        --variant meanaudio_s \
        --model_path "$S2_EMA" \
        --output "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --use_meanflow --num_steps 1 \
        --encoder_name t5_clap --text_c_dim 512 \
        --cfg_strength 0.5 --quality_level $Q \
        --full_precision \
        2>&1 | tee "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"

    # Full benchmark n=5521
    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --exp_name "${EXP_S2}_q${Q}_musiccaps" \
        --num_samples 5521 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"

    # n=2048 subset for vs P9 V2 (which used 2048)
    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --exp_name "${EXP_S2}_q${Q}_musiccaps_n2048" \
        --num_samples 2048 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"

    # ── Jamendo seed42 q=$Q ─────────────────────────────────
    EVAL_OUT_JM="$WORK_DIR/eval_output/${EXP_S2}_q${Q}_jamendo_s42"
    echo "[Eval Jamendo s42 q=$Q] gen → $EVAL_OUT_JM"

    python eval.py \
        --variant meanaudio_s \
        --model_path "$S2_EMA" \
        --output "$EVAL_OUT_JM/audio" \
        --tsv "$TSV_JAMENDO_S42" \
        --use_meanflow --num_steps 1 \
        --encoder_name t5_clap --text_c_dim 512 \
        --cfg_strength 0.5 --quality_level $Q \
        --full_precision \
        2>&1 | tee "$LOG_DIR/${EXP_S2}_q${Q}_jamendo_s42_eval.log"

    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_JM/audio" \
        --tsv "$TSV_JAMENDO_S42" \
        --exp_name "${EXP_S2}_q${Q}_jamendo_s42" \
        --num_samples 2048 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_jamendo_s42_eval.log"
done

# ============================================================
# Done
# ============================================================
echo "======================================================"
echo "  Phase 9.5 V2 done"
echo "  S2 EMA   : $S2_EMA"
echo "  Metrics  :"
echo "    MC q=6 : eval_output/metrics/${EXP_S2}_q6_musiccaps/metrics.txt"
echo "    MC q=9 : eval_output/metrics/${EXP_S2}_q9_musiccaps/metrics.txt"
echo "    JM q=6 : eval_output/metrics/${EXP_S2}_q6_jamendo_s42/metrics.txt"
echo "    JM q=9 : eval_output/metrics/${EXP_S2}_q9_jamendo_s42/metrics.txt"
echo ""
echo "  Reference baselines:"
echo "    P9 V2 bugfix MusicCaps q=9: 0.0403"
echo "    P9 V1 bugfix MusicCaps:     0.0650 (NoQ)"
echo "    P7 V1 MusicCaps q=9:        0.1975 (LP-MC, with Q)"
echo "  Note: q=N is captioner-LOCAL percentile (Qwen ≠ LP-MC bin edges)."
echo "        See ~/research/meanaudio_training/phase9_5_bin_edges.json"
echo "======================================================"
