#!/bin/bash
# ============================================================
# MeanAudio Phase 9.5 V2 — task-framed Qwen multi-cap, Q=MeanSim
# train_pipeline_phase9_5_v2.sh
#
# GATED LAUNCH (per Codex 2026-05-03 sequential gating):
#   Only launch this V2 if P9.5 V1 results show:
#     - MusicCaps CLAP > 0.0650 (better than P9 V1 bugfix), OR
#     - same-seed prompt steering ratio > 0.2 (no text-conditioning collapse)
#   If V1 already collapses, V2 will likely confirm failure → save GPU.
#
# Differences from V1:
#   - USE_Q_CONDITIONING=true (q_embed pathway active)
#   - TRAIN_TSV = phase9_5_v2_train.tsv (Qwen-local percentile q_level 0..9)
#     ↑ MUST be generated by gen_phase9_5_q_levels.py BEFORE running this
#   - Eval: q sweep {6, 9} on MusicCaps + Jamendo seed42
#     (q=6 in-support boundary, q=9 high-confidence; per P7 V1 q-sweep pattern)
#
# Pre-flight assumes:
#   - P9.5 V1 finished (so V1 NPZ + bug fixes are validated)
#   - phase9_5_v2_train.tsv exists with proper q_level (not dummy q=5)
#   - phase9_5_multicap_npz/ shared with V1 (same Qwen captions)
#
# Per Codex 2026-05-03: q=N is captioner-LOCAL percentile bucket.
#   Do NOT directly compare q=N CLAP across captioners (LP-MC vs Qwen).
#   Report raw mean_sim distribution + bin edges (saved by gen script).
#
# Usage:
#   tmux new -s p9_5_v2
#   cd ~/MeanAudio && source ~/venvs/dac/bin/activate
#   bash train_pipeline_phase9_5_v2.sh
# ============================================================

set -eo pipefail

# ============================================================
# 實驗參數
# ============================================================

EXP_PREFIX="phase9_5_v2"

BATCH_SIZE=8
ACCUM_STEPS=1

S1_ITERATIONS=400000
S2_ITERATIONS=200000

LEARNING_RATE=1e-4
USE_Q_CONDITIONING=true   # V2 trains q_embed[0..9] from MeanSim of 5 Qwen caps

# ============================================================
# 固定路徑
# ============================================================

WORK_DIR="$HOME/MeanAudio"
DATA_DIR="/mnt/HDD/kojiek/phase4_jamendo_data"
LOG_DIR="$HOME/logs"

EXP_S1="${EXP_PREFIX}_stage1_${S1_ITERATIONS}"
EXP_S2="${EXP_PREFIX}_stage2_${S2_ITERATIONS}"

S1_CKPT="$WORK_DIR/exps/$EXP_S1/${EXP_S1}_ckpt_last.pth"
S2_CKPT="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ckpt_last.pth"
S2_EMA="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ema_final.pth"

MIGRATE_SCRIPT="$WORK_DIR/migrate_stage1_to_stage2_ckpt.py"
STAGE_SCRIPT="$WORK_DIR/set_training_stage.py"

MULTICAP_NPZ="$HOME/phase9_5_multicap_npz"     # shared with V1
EVAL_SCRIPT="$HOME/research/meanaudio_eval/phase4_eval.py"

# V2-specific TSV with real Qwen-local q_level (NOT the V1 dummy)
TRAIN_TSV="$DATA_DIR/phase9_5_v2_train.tsv"
VAL_TSV="$DATA_DIR/phase4_val.tsv"
TSV_MUSICCAPS="$DATA_DIR/musiccaps_test.tsv"
TSV_JAMENDO_S42="$DATA_DIR/phase4_test_seed42_2048.tsv"

S1_MACRO=$(( S1_ITERATIONS / ACCUM_STEPS ))
S2_MACRO=$(( S2_ITERATIONS / ACCUM_STEPS ))

COMMON_ARGS=(
    batch_size=$BATCH_SIZE
    +accumulation_steps=$ACCUM_STEPS
    learning_rate=$LEARNING_RATE
    num_workers=4
    save_weights_interval=10000
    save_checkpoint_interval=20000
    +use_rope=False
    +use_wandb=False
    "+use_q_conditioning=$USE_Q_CONDITIONING"
    val_interval=999999
    eval_interval=999999
    save_eval_interval=999999
    "data.AudioCaps_npz.tsv=$TRAIN_TSV"
    "data.AudioCaps_val_npz.tsv=$VAL_TSV"
    "++data.AudioCaps_npz.npz_dir=$MULTICAP_NPZ"
    "++multi_cap=True"
)

# ============================================================
# Pre-flight 0: checkpoint overwrite guard (Codex P1 2026-05-04)
# ============================================================
S1_EMA_FINAL="$WORK_DIR/exps/$EXP_S1/${EXP_S1}_ema_final.pth"
S2_EMA_FINAL_PATH="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ema_final.pth"

if [ "${FORCE_RESTART:-0}" = "1" ]; then
    echo "[Pre-flight 0] FORCE_RESTART=1 — wiping existing exp dirs"
    rm -rf "$WORK_DIR/exps/$EXP_S1" "$WORK_DIR/exps/$EXP_S2"
elif [ -f "$S2_EMA_FINAL_PATH" ]; then
    echo "[Pre-flight 0] [ABORT] V2 already finished (S2 ema_final exists)"
    echo "  $S2_EMA_FINAL_PATH"
    exit 10
elif [ -f "$S1_EMA_FINAL" ] && [ ! -f "$S1_CKPT" ]; then
    echo "[Pre-flight 0] [ABORT] S1 ema_final exists but no ckpt_last (cannot resume safely)"
    exit 10
elif [ -f "$S1_CKPT" ] || [ -f "$S2_CKPT" ]; then
    echo "[Pre-flight 0] [INFO] existing ckpts detected — train.py will resume"
    [ -f "$S1_CKPT" ] && echo "  S1 ckpt: $S1_CKPT"
    [ -f "$S2_CKPT" ] && echo "  S2 ckpt: $S2_CKPT"
fi

mkdir -p "$LOG_DIR" "$WORK_DIR/exps/$EXP_S1" "$WORK_DIR/exps/$EXP_S2"
cd "$WORK_DIR"
export CUDA_VISIBLE_DEVICES=0

echo "======================================================"
echo "  Phase 9.5 V2 — task-framed Qwen multi-cap, Q=MeanSim"
echo "  S1 exp_id    : $EXP_S1 (from scratch, with Q)"
echo "  S2 exp_id    : $EXP_S2"
echo "  NPZ dir      : $MULTICAP_NPZ (shared with V1)"
echo "  Train TSV    : $TRAIN_TSV (Qwen-local q_level)"
echo "  use_q_cond   : $USE_Q_CONDITIONING"
echo "  Eval         : MusicCaps + Jamendo seed42, q={6,9}"
echo "======================================================"

# ============================================================
# Pre-flight A: bug fixes still applied
# ============================================================
echo "[Pre-flight A] verify bug fixes"

python -c "
import re
with open('meanaudio/model/networks.py') as f:
    code = f.read()
mf_start = code.find('class MeanAudio')
mf_code = code[mf_start:]
if re.search(r'q = torch\.full\(\([^,]+,\), 9,', mf_code):
    raise SystemExit('[FAIL] networks.py MeanAudio still fills q=9 instead of 10')
print('[OK] networks.py q=10 fix active')
"

python -c "
with open('meanaudio/runner_meanflow.py') as f:
    code = f.read()
if 'text_f_undrop = text_f.clone()' not in code or 'text_f_c_undrop = text_f_c.clone()' not in code:
    raise SystemExit('[FAIL] runner_meanflow.py text_f_undrop alias bug present')
print('[OK] runner_meanflow.py clone fix active')
"

python -c "
import re
with open('meanaudio/runner_flowmatching.py') as f:
    code = f.read()

# Codex P2 2026-05-04: not enough to grep 'q_level'. Verify the actual data
# pathway: data dict reads q_level AND that q flows into network call.
checks = []

# 1) q_level read from data dict
if not re.search(r'data\\[\\s*[\"\\']q_level[\"\\']\\s*\\]', code) and 'q_level' not in code:
    checks.append('q_level not read from data dict')

# 2) network/loss called with q=
#    historic bug: runner_flowmatching ignored q. Look for q= in network/loss call.
network_with_q = re.search(r'self\\.(network|loss_fn|fm)\\([^)]{0,400}q\\s*=\\s*q', code, re.DOTALL)
fn_with_q      = re.search(r'\\bfn\\([^)]{0,400}q\\s*=\\s*q', code, re.DOTALL)
loss_call_q    = re.search(r'\\.loss\\([^)]{0,400}q\\s*=\\s*q', code, re.DOTALL)
if not (network_with_q or fn_with_q or loss_call_q):
    checks.append('no network/fn/loss call passing q=q (q-passing fix may be missing)')

if checks:
    print('[FAIL] runner_flowmatching.py q-passing audit failed:')
    for c in checks:
        print(f'   - {c}')
    raise SystemExit(1)

# Bonus: count q references to make sure it's not dead code
n_q_refs = len(re.findall(r'\\bq_level\\b|\\bq\\s*=\\s*q\\b', code))
print(f'[OK] runner_flowmatching.py q-passing verified ({n_q_refs} q references in code)')
"

# ============================================================
# Pre-flight B: V2 train TSV — strict checks (Codex P1 2026-05-04)
# ============================================================
# 1) row count == phase7_v1_train.tsv (expected 251,599)
# 2) all q_level values are integers in {0..9} (no missing, no out-of-range)
# 3) bin populated reasonably (each bin ≥ 1% of total) — equal-freq sanity
# 4) bin_edges JSON exists with N+1 edges + per-bin counts
# 5) bin_edges source matches phase9_omni_captions.jsonl (provenance)

echo "[Pre-flight B] verify V2 train TSV has correctly binned q_level"

REF_TSV="/mnt/HDD/kojiek/phase4_jamendo_data/phase7_v1_train.tsv"
BIN_EDGES_JSON="$HOME/research/meanaudio_training/phase9_5_bin_edges.json"

if [ ! -f "$TRAIN_TSV" ]; then
    echo "[FAIL] $TRAIN_TSV not found"
    echo "       Run first: python ~/research/meanaudio_training/gen_phase9_5_q_levels.py"
    exit 1
fi

if [ ! -f "$BIN_EDGES_JSON" ]; then
    echo "[FAIL] $BIN_EDGES_JSON not found (q_levels script must have produced it)"
    echo "       Run: python ~/research/meanaudio_training/gen_phase9_5_q_levels.py"
    exit 1
fi

python - <<PYEOF
import csv, json, sys
from collections import Counter
from pathlib import Path

train_tsv = Path('$TRAIN_TSV')
ref_tsv   = Path('$REF_TSV')
bin_edges_json = Path('$BIN_EDGES_JSON')

with open(train_tsv) as f:
    rows = list(csv.DictReader(f, delimiter='\t'))
with open(ref_tsv) as f:
    ref_rows = list(csv.DictReader(f, delimiter='\t'))

n_rows = len(rows)
n_ref  = len(ref_rows)
print(f'  TSV rows: {n_rows:,}  (ref phase7_v1: {n_ref:,})')
if n_rows != n_ref:
    print(f'[FAIL] row count {n_rows:,} != ref {n_ref:,}')
    sys.exit(1)

# id order alignment
mismatches = 0
for i, (r, ref) in enumerate(zip(rows, ref_rows)):
    if r['id'] != ref['id']:
        mismatches += 1
        if mismatches <= 3:
            print(f'  [MISMATCH] idx {i}: V2={r["id"]} ref={ref["id"]}')
if mismatches:
    print(f'[FAIL] {mismatches} id-order mismatches vs phase7_v1_train.tsv')
    sys.exit(1)

# q_level integer check + range
bad = []
for i, r in enumerate(rows):
    q = r.get('q_level', '')
    try:
        qi = int(q)
        if qi < 0 or qi > 9:
            bad.append((i, q, 'out-of-range'))
    except ValueError:
        bad.append((i, q, 'non-integer'))
if bad:
    print(f'[FAIL] {len(bad)} rows have invalid q_level')
    for i, q, why in bad[:5]:
        print(f'  idx {i}: q_level={q!r} ({why})')
    sys.exit(1)

counts = Counter(int(r['q_level']) for r in rows)
print(f'  q_level distribution: {dict(sorted(counts.items()))}')

# All 10 bins should be present (equal-freq target: 10% each, allow 1% floor)
unique_q = len(counts)
floor = max(1, n_rows // 100)  # 1% of total
sparse_bins = [(q, c) for q, c in counts.items() if c < floor]
if unique_q < 10:
    missing = sorted(set(range(10)) - set(counts.keys()))
    print(f'[WARN] only {unique_q}/10 bins populated. Missing: {missing}')
    print('       (acceptable if Qwen mean_sim distribution has gaps)')
if sparse_bins:
    print(f'[WARN] sparse bins (< 1% = {floor:,}): {sparse_bins}')
print(f'[OK] {unique_q}/10 bins, all q in [0..9], rows match ref')

# bin_edges JSON structure check
with open(bin_edges_json) as f:
    bins = json.load(f)
required = ('n_bins', 'edges', 'counts_per_bin', 'fallback_q', 'source')
missing = [k for k in required if k not in bins]
if missing:
    print(f'[FAIL] bin_edges.json missing keys: {missing}')
    sys.exit(1)
n_bins = bins['n_bins']
edges  = bins['edges']
if len(edges) != n_bins + 1:
    print(f'[FAIL] edges len {len(edges)} != n_bins+1 ({n_bins+1})')
    sys.exit(1)
src = bins.get('source', '')
if 'phase9_omni_captions' not in src:
    print(f'[FAIL] bin_edges source not from Qwen merged JSONL: {src!r}')
    sys.exit(1)
print(f'[OK] bin_edges.json: {n_bins} bins, edges {edges[0]:.4f} → {edges[-1]:.4f}, src={src}')
PYEOF

# ============================================================
# Pre-flight C: NPZ
# ============================================================
echo "[Pre-flight C] verify NPZ dir"
python "$HOME/research/meanaudio_training/validate_multicap_npz.py" \
    --tsv "$TRAIN_TSV" --npz_dir "$MULTICAP_NPZ" --deep 200

# ============================================================
# Stage 1 — FluxAudio with Q (S1 trains q_embed[0..9] from data q_level)
# ============================================================
echo "[Stage 1] launching $EXP_S1"
python "$STAGE_SCRIPT" --stage 1

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=fluxaudio_s \
    exp_id="$EXP_S1" \
    num_iterations=$S1_ITERATIONS \
    "lr_schedule_steps=[320000,360000]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S1}.log"

echo "[Stage 1] done. ckpt at $S1_CKPT"

# ============================================================
# Migrate (preserves trained q_embed[0..9]) — with overwrite guard
# ============================================================
if [ -f "$S2_CKPT" ] && [ "${FORCE_MIGRATE:-0}" != "1" ]; then
    echo "[Migrate] [SKIP] $S2_CKPT already exists (set FORCE_MIGRATE=1 to overwrite)"
else
    echo "[Migrate] $S1_CKPT → $S2_CKPT"
    python "$MIGRATE_SCRIPT" --s1_ckpt "$S1_CKPT" --s2_out "$S2_CKPT"
fi

# ============================================================
# Stage 2 — MeanAudio with Q
# ============================================================
echo "[Stage 2] launching $EXP_S2"
python "$STAGE_SCRIPT" --stage 2

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=meanaudio_s \
    exp_id="$EXP_S2" \
    num_iterations=$(( S1_ITERATIONS + S2_ITERATIONS )) \
    "lr_schedule_steps=[999999,999999]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S2}.log"

echo "[Stage 2] done"

# ============================================================
# Eval (Codex P2 2026-05-04 — Qwen-local q ≠ P7 LP-MC q):
#   MusicCaps: full q sweep 5..9 (don't assume P7 support set transfers)
#   Jamendo seed42: q=6, 9 only (auxiliary)
# ============================================================
MC_Q_VALUES="${MC_Q_VALUES:-5 6 7 8 9}"
JM_Q_VALUES="${JM_Q_VALUES:-6 9}"

# ── MusicCaps q sweep ───────────────────────────────────────
for Q in $MC_Q_VALUES; do
    EVAL_OUT_MC="$WORK_DIR/eval_output/${EXP_S2}_q${Q}_musiccaps"
    echo "[Eval MusicCaps q=$Q] gen → $EVAL_OUT_MC"

    python eval.py \
        --variant meanaudio_s \
        --model_path "$S2_EMA" \
        --output "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --use_meanflow --num_steps 1 \
        --encoder_name t5_clap --text_c_dim 512 \
        --cfg_strength 0.5 --quality_level $Q \
        --full_precision \
        2>&1 | tee "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"

    # Full benchmark n=5521
    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --exp_name "${EXP_S2}_q${Q}_musiccaps" \
        --num_samples 5521 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"

    # n=2048 subset for vs P9 V2 (which used 2048)
    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_MC/audio" \
        --tsv "$TSV_MUSICCAPS" \
        --exp_name "${EXP_S2}_q${Q}_musiccaps_n2048" \
        --num_samples 2048 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_musiccaps_eval.log"
done

# ── Jamendo seed42 (auxiliary, only q=6/9) ─────────────────
for Q in $JM_Q_VALUES; do
    EVAL_OUT_JM="$WORK_DIR/eval_output/${EXP_S2}_q${Q}_jamendo_s42"
    echo "[Eval Jamendo s42 q=$Q] gen → $EVAL_OUT_JM"

    python eval.py \
        --variant meanaudio_s \
        --model_path "$S2_EMA" \
        --output "$EVAL_OUT_JM/audio" \
        --tsv "$TSV_JAMENDO_S42" \
        --use_meanflow --num_steps 1 \
        --encoder_name t5_clap --text_c_dim 512 \
        --cfg_strength 0.5 --quality_level $Q \
        --full_precision \
        2>&1 | tee "$LOG_DIR/${EXP_S2}_q${Q}_jamendo_s42_eval.log"

    python "$EVAL_SCRIPT" \
        --gen_dir "$EVAL_OUT_JM/audio" \
        --tsv "$TSV_JAMENDO_S42" \
        --exp_name "${EXP_S2}_q${Q}_jamendo_s42" \
        --num_samples 2048 \
        2>&1 | tee -a "$LOG_DIR/${EXP_S2}_q${Q}_jamendo_s42_eval.log"
done

# ============================================================
# Done
# ============================================================
echo "======================================================"
echo "  Phase 9.5 V2 done"
echo "  S2 EMA   : $S2_EMA"
echo "  Metrics  :"
echo "    MC q=6 : eval_output/metrics/${EXP_S2}_q6_musiccaps/metrics.txt"
echo "    MC q=9 : eval_output/metrics/${EXP_S2}_q9_musiccaps/metrics.txt"
echo "    JM q=6 : eval_output/metrics/${EXP_S2}_q6_jamendo_s42/metrics.txt"
echo "    JM q=9 : eval_output/metrics/${EXP_S2}_q9_jamendo_s42/metrics.txt"
echo ""
echo "  Reference baselines:"
echo "    P9 V2 bugfix MusicCaps q=9: 0.0403"
echo "    P9 V1 bugfix MusicCaps:     0.0650 (NoQ)"
echo "    P7 V1 MusicCaps q=9:        0.1975 (LP-MC, with Q)"
echo "  Note: q=N is captioner-LOCAL percentile (Qwen ≠ LP-MC bin edges)."
echo "        See ~/research/meanaudio_training/phase9_5_bin_edges.json"
echo "======================================================"
