#!/bin/bash
# HISTORICAL INVALID PIPELINE (2026-07-16): P9.5 used the same positional
# multi-caption cache-writer bug. Its 0.0609 result is excluded.
# ============================================================
# MeanAudio Phase 9.5 V1 — task-framed Qwen multi-cap, NoQ
# train_pipeline_phase9_5_v1.sh
#
# Per Codex 2026-05-03 review:
#   - Retrain S1 from scratch on Qwen NPZ (NOT reuse P9 V1 LP-MC S1)
#   - NoQ throughout (TSV q_level column is ignored when use_q_conditioning=false)
#   - Dual eval: MusicCaps n=5527 (primary) + Jamendo seed42 2048 (secondary)
#
# Sequential gating: only launch P9.5 V2 (Q variant) after this V1 result
# shows either CLAP > P9 V1 bugfix (0.0650 MusicCaps) OR same-seed prompt
# steering ratio > 0.2 (no collapse).
#
# Pre-flight assumes:
#   - sanity_qwen_jsonl.py passed
#   - phase9_5_train.tsv generated by gen_phase9_5_q_levels.py
#   - phase9_5_multicap_npz/ generated by gen_multicap_npz.py
#   - All bug fixes active (networks.py q=10, runner_meanflow.py clone,
#     runner_flowmatching.py q passing)
#
# Usage:
#   tmux new -s p9_5_v1
#   cd ~/MeanAudio && source ~/venvs/dac/bin/activate
#   bash train_pipeline_phase9_5_v1.sh
# ============================================================

set -eo pipefail

if [ "${ALLOW_INVALID_HISTORICAL_P9:-0}" != "1" ]; then
    echo "[ABORT] Historical P9.5 multi-cap cache is audio-caption misaligned."
    echo "Its 0.0609 result is excluded; rebuild a canonical v2 cache first."
    exit 64
fi

# ============================================================
# 實驗參數
# ============================================================

EXP_PREFIX="phase9_5_v1"

BATCH_SIZE=8
ACCUM_STEPS=1

S1_ITERATIONS=400000
S2_ITERATIONS=200000

LEARNING_RATE=1e-4
USE_Q_CONDITIONING=false

# ============================================================
# 固定路徑
# ============================================================

WORK_DIR="$HOME/MeanAudio"
DATA_DIR="/mnt/HDD/kojiek/phase4_jamendo_data"
LOG_DIR="$HOME/logs"

EXP_S1="${EXP_PREFIX}_stage1_${S1_ITERATIONS}"
EXP_S2="${EXP_PREFIX}_stage2_${S2_ITERATIONS}"

S1_CKPT="$WORK_DIR/exps/$EXP_S1/${EXP_S1}_ckpt_last.pth"
S2_CKPT="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ckpt_last.pth"
S2_EMA="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ema_final.pth"

MIGRATE_SCRIPT="$WORK_DIR/migrate_stage1_to_stage2_ckpt.py"
STAGE_SCRIPT="$WORK_DIR/set_training_stage.py"

MULTICAP_NPZ="$HOME/phase9_5_multicap_npz"
EVAL_SCRIPT="$HOME/research/meanaudio_eval/phase4_eval.py"

TRAIN_TSV="$DATA_DIR/phase9_5_train.tsv"
VAL_TSV="$DATA_DIR/phase4_val.tsv"
TSV_MUSICCAPS="$DATA_DIR/musiccaps_test.tsv"
TSV_JAMENDO_S42="$DATA_DIR/phase4_test_seed42_2048.tsv"

S1_MACRO=$(( S1_ITERATIONS / ACCUM_STEPS ))
S2_MACRO=$(( S2_ITERATIONS / ACCUM_STEPS ))

COMMON_ARGS=(
    batch_size=$BATCH_SIZE
    +accumulation_steps=$ACCUM_STEPS
    learning_rate=$LEARNING_RATE
    num_workers=4
    save_weights_interval=10000
    save_checkpoint_interval=20000
    +use_rope=False
    +use_wandb=False
    "+use_q_conditioning=$USE_Q_CONDITIONING"
    val_interval=999999
    eval_interval=999999
    save_eval_interval=999999
    "data.AudioCaps_npz.tsv=$TRAIN_TSV"
    "data.AudioCaps_val_npz.tsv=$VAL_TSV"
    "++data.AudioCaps_npz.npz_dir=$MULTICAP_NPZ"
    "++multi_cap=True"
)

# ============================================================
# Pre-flight 0: checkpoint overwrite guard (Codex P1 2026-05-04)
# ============================================================
# Refuse to overwrite existing finished work unless explicitly forced.
# Checks both ckpt_last.pth (resumable) and ema_final.pth (finished signal).
# Set FORCE_RESTART=1 to start over (deletes existing exp dirs first).
# Set FORCE_MIGRATE=1 to allow migrate to overwrite an existing S2 ckpt.

S1_EMA_FINAL="$WORK_DIR/exps/$EXP_S1/${EXP_S1}_ema_final.pth"
S2_EMA_FINAL_PATH="$WORK_DIR/exps/$EXP_S2/${EXP_S2}_ema_final.pth"

if [ "${FORCE_RESTART:-0}" = "1" ]; then
    echo "[Pre-flight 0] FORCE_RESTART=1 — wiping existing exp dirs"
    rm -rf "$WORK_DIR/exps/$EXP_S1" "$WORK_DIR/exps/$EXP_S2"
elif [ -f "$S2_EMA_FINAL_PATH" ]; then
    echo "[Pre-flight 0] [ABORT] S2 ema_final exists — V1 already finished"
    echo "  $S2_EMA_FINAL_PATH"
    echo "  Set FORCE_RESTART=1 to retrain from scratch (will DELETE exp dirs)."
    exit 10
elif [ -f "$S1_EMA_FINAL" ] && [ ! -f "$S1_CKPT" ]; then
    echo "[Pre-flight 0] [ABORT] S1 ema_final exists but no ckpt_last (cannot resume safely)"
    echo "  $S1_EMA_FINAL"
    echo "  Set FORCE_RESTART=1 to retrain from scratch."
    exit 10
elif [ -f "$S1_CKPT" ] || [ -f "$S2_CKPT" ]; then
    echo "[Pre-flight 0] [INFO] existing ckpts detected — train.py will resume from ckpt_last"
    [ -f "$S1_CKPT" ] && echo "  S1 ckpt: $S1_CKPT"
    [ -f "$S2_CKPT" ] && echo "  S2 ckpt: $S2_CKPT"
fi

mkdir -p "$LOG_DIR" "$WORK_DIR/exps/$EXP_S1" "$WORK_DIR/exps/$EXP_S2"
cd "$WORK_DIR"
export CUDA_VISIBLE_DEVICES=0

echo "======================================================"
echo "  Phase 9.5 V1 — task-framed Qwen multi-cap, NoQ"
echo "  S1 exp_id    : $EXP_S1 (from scratch)"
echo "  S2 exp_id    : $EXP_S2"
echo "  NPZ dir      : $MULTICAP_NPZ"
echo "  Train TSV    : $TRAIN_TSV"
echo "  use_q_cond   : $USE_Q_CONDITIONING"
echo "  Eval MusicCaps : $TSV_MUSICCAPS"
echo "  Eval Jamendo s42: $TSV_JAMENDO_S42"
echo "======================================================"

# ============================================================
# Pre-flight: bug fixes still applied
# ============================================================
echo "[Pre-flight A] verify bug fixes"

python -c "
import re
with open('meanaudio/model/networks.py') as f:
    code = f.read()
mf_start = code.find('class MeanAudio')
mf_code = code[mf_start:]
if re.search(r'q = torch\.full\(\([^,]+,\), 9,', mf_code):
    raise SystemExit('[FAIL] networks.py MeanAudio still fills q=9 instead of 10')
print('[OK] networks.py q=10 fix active')
"

python -c "
with open('meanaudio/runner_meanflow.py') as f:
    code = f.read()
if 'text_f_undrop = text_f.clone()' not in code or 'text_f_c_undrop = text_f_c.clone()' not in code:
    raise SystemExit('[FAIL] runner_meanflow.py text_f_undrop alias bug present')
print('[OK] runner_meanflow.py clone fix active')
"

python -c "
with open('meanaudio/runner_flowmatching.py') as f:
    code = f.read()
if 'q_level' not in code:
    raise SystemExit('[FAIL] runner_flowmatching.py missing q_level reads')
print('[OK] runner_flowmatching.py q passing active')
"

# ============================================================
# Pre-flight: NPZ + TSV
# ============================================================
echo "[Pre-flight B] verify NPZ dir + TSV"
python "$HOME/research/meanaudio_training/validate_multicap_npz.py" \
    --tsv "$TRAIN_TSV" --npz_dir "$MULTICAP_NPZ" --deep 200

# ============================================================
# Stage 1 — FluxAudio (Flow Matching), no r param
# ============================================================
echo "[Stage 1] launching $EXP_S1"
python "$STAGE_SCRIPT" --stage 1

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=fluxaudio_s \
    exp_id="$EXP_S1" \
    num_iterations=$S1_ITERATIONS \
    "lr_schedule_steps=[320000,360000]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S1}.log"

echo "[Stage 1] done. ckpt at $S1_CKPT"

# ============================================================
# Migrate (with overwrite guard)
# ============================================================
if [ -f "$S2_CKPT" ] && [ "${FORCE_MIGRATE:-0}" != "1" ]; then
    echo "[Migrate] [SKIP] $S2_CKPT already exists (set FORCE_MIGRATE=1 to overwrite)"
else
    echo "[Migrate] $S1_CKPT → $S2_CKPT"
    python "$MIGRATE_SCRIPT" --s1_ckpt "$S1_CKPT" --s2_out "$S2_CKPT"
fi

# ============================================================
# Stage 2
# ============================================================
echo "[Stage 2] launching $EXP_S2"
python "$STAGE_SCRIPT" --stage 2

torchrun --standalone --nproc_per_node=1 train.py \
    data=meanaudio \
    model=meanaudio_s \
    exp_id="$EXP_S2" \
    num_iterations=$(( S1_ITERATIONS + S2_ITERATIONS )) \
    "lr_schedule_steps=[999999,999999]" \
    "${COMMON_ARGS[@]}" \
    2>&1 | tee "$LOG_DIR/${EXP_S2}.log"

echo "[Stage 2] done"

# ============================================================
# Eval #1: MusicCaps (primary)
# ============================================================
EVAL_OUT_MC="$WORK_DIR/eval_output/${EXP_S2}_musiccaps"
echo "[Eval MusicCaps] generating → $EVAL_OUT_MC"

python eval.py \
    --variant meanaudio_s \
    --model_path "$S2_EMA" \
    --output "$EVAL_OUT_MC/audio" \
    --tsv "$TSV_MUSICCAPS" \
    --use_meanflow --num_steps 1 \
    --encoder_name t5_clap --text_c_dim 512 \
    --cfg_strength 0.5 --no_q \
    --full_precision \
    2>&1 | tee "$LOG_DIR/${EXP_S2}_musiccaps_eval.log"

python "$EVAL_SCRIPT" \
    --gen_dir "$EVAL_OUT_MC/audio" \
    --tsv "$TSV_MUSICCAPS" \
    --exp_name "${EXP_S2}_musiccaps" \
    --num_samples 5521 \
    2>&1 | tee -a "$LOG_DIR/${EXP_S2}_musiccaps_eval.log"

# Also compute n=2048 subset for apples-to-apples comparison vs P9 V1 bugfix (0.0650 baseline)
python "$EVAL_SCRIPT" \
    --gen_dir "$EVAL_OUT_MC/audio" \
    --tsv "$TSV_MUSICCAPS" \
    --exp_name "${EXP_S2}_musiccaps_n2048" \
    --num_samples 2048 \
    2>&1 | tee -a "$LOG_DIR/${EXP_S2}_musiccaps_eval.log"

# ============================================================
# Eval #2: Jamendo seed42 2048 (secondary, for in-domain sanity vs P7/P8/P9)
# ============================================================
EVAL_OUT_JM="$WORK_DIR/eval_output/${EXP_S2}_jamendo_s42"
echo "[Eval Jamendo s42] generating → $EVAL_OUT_JM"

python eval.py \
    --variant meanaudio_s \
    --model_path "$S2_EMA" \
    --output "$EVAL_OUT_JM/audio" \
    --tsv "$TSV_JAMENDO_S42" \
    --use_meanflow --num_steps 1 \
    --encoder_name t5_clap --text_c_dim 512 \
    --cfg_strength 0.5 --no_q \
    --full_precision \
    2>&1 | tee "$LOG_DIR/${EXP_S2}_jamendo_s42_eval.log"

python "$EVAL_SCRIPT" \
    --gen_dir "$EVAL_OUT_JM/audio" \
    --tsv "$TSV_JAMENDO_S42" \
    --exp_name "${EXP_S2}_jamendo_s42" \
    --num_samples 2048 \
    2>&1 | tee -a "$LOG_DIR/${EXP_S2}_jamendo_s42_eval.log"

# ============================================================
# Done
# ============================================================
echo "======================================================"
echo "  Phase 9.5 V1 done"
echo "  S2 EMA   : $S2_EMA"
echo "  Metrics  : eval_output/metrics/${EXP_S2}_musiccaps/metrics.txt"
echo "             eval_output/metrics/${EXP_S2}_jamendo_s42/metrics.txt"
echo ""
echo "  Reference baselines:"
echo "    P9 V1 bugfix MusicCaps CLAP : 0.0650"
echo "    P8 NoQ MusicCaps CLAP       : 0.1851"
echo "    P7 V1 MusicCaps CLAP        : 0.1975 (with Q)"
echo ""
echo "  V2 launch gate (Codex 2026-05-03):"
echo "    only launch P9.5 V2 if V1 CLAP > 0.0650"
echo "    OR same-seed prompt steering ratio > 0.2"
echo "======================================================"
